### ISSUE TITLE
Définir les algorithmes à utiliser pour le positionnement

### ISSUE THREAD

**Issue by vililichi** [Neorobrooke/neorobrooke-s4#1]
-Obtention de position
-Modification de position

critère: Un code/ pseudo code/ UML décrivant les opérations

**Comment by vililichi** [comment]
critère:  Un code/ pseudo code/ UML décrivant les opération

**Comment by philippewarren** [comment]
Commentaires de review:
- Allonger les noms des variables, tu as un bon IDE qui complète de toute façon, et "u" ou "est" est pas très clair
- Éviter les blocs `if` ou `for` sur une seule ligne. C'est beaucoup plus lisible quand c'est bien formaté.
```cpp
// Illisible
if (grosmachintroplongetcompliqué)throw 1; // problème de truc

// Mieux
// Problème de truc
if (grosmachintroplongetcompliqué)
    throw 1;

// Encore mieux
// Problème de truc
if (grosmachintroplongetcompliqué)
{
    throw 1;
}
```
- Encoder les fichiers de code en UTF-8
- Commencer les commentaires avec des majuscules et un espace: `// Truc` au lieu de `//truc`, et mettre les accents dans les mots dans les commentaires (il y en a la moitié actuellement, câble et pôle prennent un accent)
- Mettre des lignes vides pour séparer les groupes logiques et segments de code qui ont un lien
- Remplacer les `throw n` par un système de codes d'erreurs (ça va tourner sur Arduino)

**Comment by philippewarren** [comment]
@vililichi 
Voici [un lien vers un premier code review.](https://github.com/Neorobrooke/neorobrooke-s4/pull/42#pullrequestreview-586026993)
Je te propose de commencer par ça, entre autre, mettre des noms plus explicites aux variables et mieux expliquer l'algorithme à l'aide d'un commentaire multilignes quand c'est un peu complexe.
Une fois que ce sera fait, ça va être pas mal plus facile de valider ton algo.

**Comment by philippewarren** [comment]
Review -> 1h
