### ISSUE TITLE
Mise à jour du manuel d'utilisateur

### ISSUE THREAD

**Issue by mrscamille** [Neorobrooke/neorobrooke-s4#107]

**Comment by mrscamille** [comment]
3 h Camille, modification des parties:
- Électrique
  - Modification OpenCR
  - Ajout de la partie encodeur
- Bobine
  - Modification image bobine pour la nouvelle
- Support moteur
  - Modification image support pour le nouveau

Manque
 - Support moteur assemblé (image finale)
 - Support encodeur : tous
 - partie logiciel : à vérifier

**Comment by GabrielDore** [comment]
Partie validé:
- Électrique
  - Modification OpenCR
  - Ajout de la partie encodeur
- Bobine
  - Modification image bobine pour la nouvelle
- Support moteur
  - Modification image support pour le nouveau
  - Support moteur assemblé (image finale)
  - Support encodeur : tous

Manque:
 - partie logiciel : à vérifier

**Comment by philippewarren** [comment]
Avancement de la partie logicielle -> 30 minutes

**Comment by philippewarren** [comment]
Partie logicielle et amélioration de pip_script pour faciliter l'installation -> 45 min

**Comment by philippewarren** [comment]
Ajout d'un "getting started" et mise à jour de la partie API -> 1h30

**Comment by mrscamille** [comment]
Keven:
* manque prendre des photos pour la partie calibration du manuel d'utilisation (mercredi)
* assemblage des câble
* assemblage de la nacelle
