### ISSUE TITLE
Choix des limit-switch 

### ISSUE THREAD

**Issue by GabrielDore** [Neorobrooke/neorobrooke-s4#11]
Faire le choix des limit-switch qui sont installer sur les systèmes de poulies pour éviter de faire forcer les moteurs.

**Comment by williambruneau27** [comment]
https://www.banggood.com/5Pcs-SS-5GL-Micro-Limit-Switch-ENDSTOP-RAMPS-1_4-Omron-For-3D-Printer-Accessories-p-1755147.html?cur_warehouse=CN&rmmds=search
![image.png](https://images.zenhubusercontent.com/60084d0b4381307841ea7981/9126e01c-e5e6-4d7c-b79a-4c4092602ba4)
![image.png](https://images.zenhubusercontent.com/60084d0b4381307841ea7981/714efe60-731b-4c90-86f3-4dd2219f6a6e)

**Comment by philippewarren** [comment]
Inutile, abandonné.
