### ISSUE TITLE
Ménage dans le GitHub

### ISSUE THREAD

**Issue by mrscamille** [Neorobrooke/neorobrooke-s4#113]

**Comment by mrscamille** [comment]
**Partie CAD**
* Bobine --> fait
* Électrique --> fait
* Encodeur
* Nacelle 2D --> fait
* Nacelle 3D --> fait
* Pilier --> fait
* Serre fil
* Structure --> fait
* Support moteur --> fait
* Support cadre

**Comment by philippewarren** [comment]
@vililichi Faudrait checker pour les fichiers de code C++ en double (positionnnement et codeMicrocontroleur).

**Comment by philippewarren** [comment]
@williambruneau27 Je propose d'enlever la partie UI, ce qui permet de ne pas considérer la compliance avec la license de Qt. J'enlèverais aussi le pptx, qui n'est pas tant pertinant seul.
