### ISSUE TITLE
Définir les plateformes utilisées pour tourner les codes

### ISSUE THREAD

**Issue by vililichi** [Neorobrooke/neorobrooke-s4#14]

**Comment by philippewarren** [comment]
Distribution du code:
	-	Tout tourne sur le microcontrôleur.
	-	On communique par port série avec un ordinateur quelconque.
	-	On fait une librairie Arduino, avec une API en Python, C++, C.
	-	Pour notre projet, on va utiliser un Raspberry Pi pour la partie pas-Arduino
		.	Implique de faire de la doc pour l'utiliser avec un Pi
		.	Pour tester, on va surtout faire ça sur nos ordis
