### ISSUE TITLE
CAD de la charge en 3D

### ISSUE THREAD

**Issue by williambruneau27** [Neorobrooke/neorobrooke-s4#22]
Cette pièce aura 4 points d'attache et aura des dimensions extérieures immuables. La première version de cette charge pourra accueillir un poids pour faire des tests.

**Comment by williambruneau27** [comment]
![image.png](https://images.zenhubusercontent.com/60084d0b4381307841ea7981/4d1a7730-ef9d-41b7-b9b4-ff678a6c4ed9)

**Comment by philippewarren** [comment]
Mise en plan et CAD disponibles sur github.
