### ISSUE TITLE
CAD de la charge en 2D

### ISSUE THREAD

**Issue by philippewarren** [Neorobrooke/neorobrooke-s4#23]

**Comment by monp1202** [comment]
![nacelle 2D.PNG](https://images.zenhubusercontent.com/60084cd1c8db73e178c3410c/3957b01f-bc8b-4951-9aff-d4306bb3d04a)

longueur : 100 mm
largeur : 30 mm 
trou : 5 mm diamètre
hauteur : 50 mm
