### ISSUE TITLE
Prévoir une liste de matériel à acheter

### ISSUE THREAD

**Issue by philippewarren** [Neorobrooke/neorobrooke-s4#24]
Préparer une liste pour Electro 5 et/ou quincaillerie.

**Comment by monp1202** [comment]
- bois 2x2 pour pilier 4 m (4 fois 1 m)
- bois 2x2 pour traverse 6 m (4 fois 1.5 m)
- bois 2x2 pour base 45° 1.20 m (8 *0.15 m)
- plaque de bois pour surface de base 0.2x0.2 x 4 piliers
- vis 1.5 pouces (45° à pilier)
- vis ?? (45° à planche)
- U en métal + vis, 8 fois
- anneau de métal 4 fois

**Comment by williambruneau27** [comment]
AJOUTER une boite d'écrous pour boulon sélectionné
