### ISSUE TITLE
Porter le code pour OpenCR

### ISSUE THREAD

**Issue by philippewarren** [Neorobrooke/neorobrooke-s4#27]
Remplacer les `throw`, les accès à la `std` et les affichages `cout` ou `printf` par des communications JSON de messages ou de messages d'erreur
S'assurer que ça compile sur OpenCR (possibilité de tester avec le Arduino si on a pas le OpenCR)

CRITÈRES:
- Projet PlatformIO créé, avec les fichiers de projet partagés disponibles sur git (comme le fichier de dépendances)
- Code de la librairie qui compile sur Arduino ou OpenCR et qui fonctionne (Serial.println pour voir si ça fonctionne en attendant d'avoir de la comm JSON)

**Comment by vililichi** [comment]
ajout d'un système de gestion des erreurs n'utilisant pas les exeptions
