### ISSUE TITLE
Définir la communication série

### ISSUE THREAD

**Issue by philippewarren** [Neorobrooke/neorobrooke-s4#28]
Définir le format du JSON pour la communication série. Déterminer si on prend une librairie JSON (par exemple, comme le projet S3) ou si on fait un parseur (long pour rien selon moi).

CRITÈRES:
- Format JSON défini dans un fichier, avec les commandes, valeurs possibles, type des valeurs
- librairie JSON choisie pour l'OpenCR
- librairie JSON choisie pour Python

**Comment by philippewarren** [comment]
Voici le premier jet de la [spécification pour la communication série via JSON.](https://github.com/Neorobrooke/neorobrooke-s4/blob/api-python/documentation/communication_serie.md)

**Comment by philippewarren** [comment]
Rédaction -> 2h

**Comment by philippewarren** [comment]
À AJOUTER:
- Ajouter la vitesse au déplacement dans une direction ou pour changer la position, si on le permet dans l'API plus tard.

**Comment by vililichi** [comment]
Penser à ajouter un paramêtre de vitesse pour les déplacement

**Comment by philippewarren** [comment]
@vililichi Es-tu sûr qu'on peut se permettre d'offrir plusieurs vitesses? Il faudrait connaître pour tous les points dans notre zone de travail la plage de vitesses dont chaque moteur a besoin, trouver la valeur `delta` telle qui est la différence entre le plus lent moteur et le plus rapide moteur, en tout temps, et fournir à l'utilisateur la possibilité de choisir une vitesse entre `0 + delta` et `vitesse_max_moteur - delta` comme vitesse de déplacement.
En poussant encore plus loin, on pourrait offrir des vitesses différentes selon les points, et dans ce cas, on aurait plus nécessairement des vitesses constantes si on ajuste dynamiquement (sauf si on offre un paramètre pour forcer une vitesse constante).
Ou alors, on va toujours à 50% des moteurs, avec autant de lousse des deux côtés, en tout temps, pour ajuster les différentiels entre les moteurs.

**Comment by philippewarren** [comment]
À changer pour les erreurs: obtenir une erreur à la fois, et combien il en reste.
 Ajouter majeur ou mineure, et le moment de l'erreur (temps).

**Comment by philippewarren** [comment]
On ne met pas de vitesse modifiable via l'API pour l'instant.
