### ISSUE TITLE
Définir la masse maximale de la charge 

### ISSUE THREAD

**Issue by monp1202** [Neorobrooke/neorobrooke-s4#3]
Faire en fonction de la force des moteurs, de la structure et des actions voulues

**Comment by williambruneau27** [comment]
Je suggère que le poids max soit de 500g. Ceci nous laisse de la marge de manœuvre pour ajouter un outil, un moteur ainsi que deux cellules lithium-ion.

**Comment by philippewarren** [comment]
On a choisi de définir la masse selon la hauteur, mais on aimerait environ 1 kg (ajustable).
