### ISSUE TITLE
Ajouter des tests unitaires sur la librairie en Arduino

### ISSUE THREAD

**Issue by philippewarren** [Neorobrooke/neorobrooke-s4#31]
Créer un mock des classes/fonctions des encodeurs et des moteurs pour un scénario de tests.
Ajouter des scénarios de test.

CRITÈRES:
- Un projet de tests avec Google Test qui simule les encodeurs et les moteurs et qui teste la librairie de façon extensive
- Tous les tests sont répétables (pas de tests flaky si possible)

**Comment by vililichi** [comment]
Function de test pour les fonctions:
sqrt()
abs()
getPosition()
deplacementDirectionnel()
deplacementPosition()

**Comment by vililichi** [comment]
programme de test automatique pour les calculs de la classe Funibot et test manuel pour la communication : [https://app.zenhub.com/files/329703737/5e1f8345-840b-419d-a0a6-174cfcccfb54/download](https://app.zenhub.com/files/329703737/5e1f8345-840b-419d-a0a6-174cfcccfb54/download)
