### ISSUE TITLE
Créer présentation

### ISSUE THREAD

**Issue by monp1202** [Neorobrooke/neorobrooke-s4#38]
- Valider les points de la présentation
- Créer PowerPoint

**Comment by philippewarren** [comment]
MORT

**Comment by williambruneau27** [comment]
![image.png](https://images.zenhubusercontent.com/60084d0b4381307841ea7981/14e7b533-7672-4ff9-b15c-3231ccde4ef5)

**Comment by williambruneau27** [comment]
![image.png](https://images.zenhubusercontent.com/60084d0b4381307841ea7981/9ee15190-26fd-47b5-b825-736574ee91c1)
