### ISSUE TITLE
Définir le mode d'alimentation du système

### ISSUE THREAD

**Issue by GabrielDore** [Neorobrooke/neorobrooke-s4#5]
Choix d'alimentation pour alimenter les moteurs, les encodeurs et possiblement la charge(si besoin)

**Comment by mrscamille** [comment]
Alimentation ( au min 2x120V)
* OpenCR : 12V 4.5A (power supply 120V to 12V) -> fourni par l'école
* Moteur : OpenCR connecteur RS485 (à valider avec tests) -> fourni par l'école
* Encodeur : 5V --> OpenCR (à valider) -> fourni par l'école
* PI : 5 V 2.5A (power supply 120V to 5V) -> fourni par étudiant

**Comment by GabrielDore** [comment]
Alimentation (au min 2x120V)

* OpenCR : 12V 4.5A (power supply 120V to 12V) -> fourni par l'école
	Moteur 	: OpenCR port TTL (valider avec tests) -> fourni par l'école
     	Encodeur: 5V-> OpenCR (valider) -> fourni par l'école
* PI : 5 V 2.5A (power supply 120V to 5V) -> fourni par étudiant
