### ISSUE TITLE
Plan / CAD d'assemblage

### ISSUE THREAD

**Issue by williambruneau27** [Neorobrooke/neorobrooke-s4#51]
Réaliser les plans de montage de toutes les pièces imprimées en 3D et de la structure en bois

**Comment by monp1202** [comment]
-Mise en plan bobine : faite
![image.png](https://images.zenhubusercontent.com/60084cd1c8db73e178c3410c/87037f24-2273-4901-8cde-7560464bba17)

-Mise en plan support : faite
![image.png](https://images.zenhubusercontent.com/60084cd1c8db73e178c3410c/971e656c-72ba-490c-a342-9937ec9011a7)

**Comment by williambruneau27** [comment]
![image.png](https://images.zenhubusercontent.com/60084d0b4381307841ea7981/0de96381-e5ff-43aa-9d11-b29846050f16)

**Comment by williambruneau27** [comment]
![image.png](https://images.zenhubusercontent.com/60084d0b4381307841ea7981/268bf062-5d4c-492d-af4a-4d035944e100)
