### ISSUE TITLE
Programme de test / démo utilisant l'API

### ISSUE THREAD

**Issue by williambruneau27** [Neorobrooke/neorobrooke-s4#58]
Implémenter en Python un programme de tests CLI utilisant l'API

CRITÈRES:
- Avoir un programme de tests CLI qui implémente les commandes définies dans [ce fichier.](https://github.com/Neorobrooke/neorobrooke-s4/blob/main/documentation/application_CLI_tests.md)

**Comment by philippewarren** [comment]
Développement -> 3h

**Comment by philippewarren** [comment]
Développement (21 février) -> 1h30

**Comment by philippewarren** [comment]
Ajouter les commandes prévues dans la préparation qui ne sont pas encore intégrée.
Ajouter les nouvelles commandes à la documentation du programme CLI.

**Comment by philippewarren** [comment]
Développement -> 2h
