### ISSUE TITLE
CAD poteau

### ISSUE THREAD

**Issue by monp1202** [Neorobrooke/neorobrooke-s4#6]
Faire le CAD d'un poteau sans aucune composante:
- pied
- poteau
- support à la base

**Comment by williambruneau27** [comment]
![image.png](https://images.zenhubusercontent.com/60084d0b4381307841ea7981/a7f98ddc-8738-4d3b-8fe2-3437aa921a7c)

**Comment by williambruneau27** [comment]
Un nouveau CAD sera fait le 10 février

**Comment by williambruneau27** [comment]
Version #2 
![image.png](https://images.zenhubusercontent.com/60084d0b4381307841ea7981/c68eb6c3-7f4a-495c-a9ca-97a0a9b53b1d)
