### ISSUE TITLE
Définir les requis pour faire une librairie

### ISSUE THREAD

**Issue by vililichi** [Neorobrooke/neorobrooke-s4#8]

**Comment by philippewarren** [comment]
Faire une librairie en C/C++ dans un module Python était assez compliqué. De plus, la plupart de notre code va être sur Arduino de toute façon. On va donc simplement faire une librairie en Python et une en C++ pour parler au Arduino. À voir si on en fait aussi une en C.

**Comment by philippewarren** [comment]
François semble dire que c'est parfaitement possible dans le cadre du projet de faire un module Python en C++, ça pourra être reconsidéré plus tard au besoin.
