### ISSUE TITLE
Planifier le GUI

### ISSUE THREAD

**Issue by philippewarren** [Neorobrooke/neorobrooke-s4#84]
Planifier le workflow du programme GUI:
- Fonctionnalités offertes
  - Et de quelle façon elles sont offertes
- Présentation visuelle (préliminaire)
- Fichier de configuration
  - Existe ou pas
  - Quels paramètres y sont contenus
  - Intechangeable avec le fichier de config du programme CLI?

Critères:
- Un document ou un commentaire présentant les requis pour l'utilisation du programme GUI

**Comment by williambruneau27** [comment]
**Idées pour le GUI**

Données reçues par le système :

- Position en 3D estimée par le système
- État en cours (En déplacement, en attente d'une commande, en erreur)
- Détails sur l'erreur suite à une commande fautive

Données envoyées au système :

- Mini terminal avec intégration du CLI
- Arrêt d'urgence
- Bouton qui active le déplacement par WASD (et qui désactive le terminal en même temps)

**Comment by philippewarren** [comment]
Préparer une copie du code source de Qt pour respecter le LGPLv3, débogage et corrections, tests sur l'algo de Keven -> 6h30

**Comment by philippewarren** [comment]
Abandoné.
