### ISSUE TITLE
Définir les opérations offert par l'API

### ISSUE THREAD

**Issue by vililichi** [Neorobrooke/neorobrooke-s4#9]

**Comment by philippewarren** [comment]
-	Instancier plusieurs robots
		.	Port série pour chacun
		.	Coordonnées des poteaux pour chacun
	-	Calibrer
		.	Manuellement dans un premier temps
		.	Automatiquement plus tard?
	-	Obtenir la position de la charge
	-	Déplacer à une position
	-	Déplacer dans une direction
		.	D'une certaine distance
		.	Jusqu'à ce qu'on demande d'arrêter
	-	Accéder aux erreurs et aux messages d'erreurs
		.	Un peu comme les erreurs de FILE* en C

**Comment by philippewarren** [comment]
[Voir la définition proposée ici.](https://github.com/Neorobrooke/neorobrooke-s4/blob/documentation-api/documentation/API.md)

**Comment by GabrielDore** [comment]
C'est good
